import {
  createAsyncThunk,
  createSlice,
  createEntityAdapter,
  PayloadAction,
  createSelector,
} from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import {
  getJobs as getJobsAPI,
  getJob as getJobAPI,
  patchJob as patchJobAPI,
  cancelJob as cancelJobAPI,
} from './api';
import { Job, IdType, JobsRequestResult } from '../../types';
import { getScanJobs as getScanJobsAPI } from '../scans/api';
import { DateTime } from 'luxon';

export const jobsAdapter = createEntityAdapter<Job>();

export interface JobsState
  extends ReturnType<(typeof jobsAdapter)['getInitialState']> {
  status: 'idle' | 'loading' | 'complete';
  totalCount: number;
}

const initialState: JobsState = jobsAdapter.getInitialState({
  status: 'idle',
  totalCount: -1,
});

export const getJobs = createAsyncThunk<
  JobsRequestResult,
  {
    skip: number;
    limit: number;
    jobType?: JobType;
    start?: DateTime;
    end?: DateTime;
  }
>('jobs/fetch', async (_payload, _thunkAPI) => {
  const { skip, limit, jobType, start, end } = _payload;
  const result = await getJobsAPI(skip, limit, jobType, start, end);

  return result;
});

export const getJob = createAsyncThunk<Job, { id: IdType }>(
  'job/fetch',
  async (payload, _thunkAPI) => {
    const { id } = payload;
    const job = await getJobAPI(id);

    return job;
  }
);

export const getJobsByScanId = createAsyncThunk<
  Job[],
  {
    scanId: IdType;
  }
>('jobs/fetchByScanId', async (payload, _thunkAPI) => {
  const { scanId } = payload;
  const result = await getScanJobsAPI(scanId);

  return result;
});

export const patchJob = createAsyncThunk<
  Job,
  { id: IdType; updates: Partial<Job> }
>('jobs/patch', async (payload, _thunkAPI) => {
  const { id, updates } = payload;
  const scan = await patchJobAPI(id, updates);

  return scan;
});

export const cancelJob = createAsyncThunk<Job, { id: IdType }>(
  'jobs/delete',
  async (payload, _thunkAPI) => {
    const { id } = payload;
    const scan = await cancelJobAPI(id);

    return scan;
  }
);

export const jobsSlice = createSlice({
  name: 'jobs',
  initialState,
  reducers: {
    setJob(state, action: PayloadAction<Job>) {
      state.totalCount = state.totalCount + 1;
      jobsAdapter.setOne(state, action.payload);
      state.ids = state.ids.sort((a, b) => Number(b) - Number(a)); // sort ids in descending order
    },
    updateJob(state, action: PayloadAction<Partial<Job>>) {
      const { id, ...changes } = action.payload;
      if (id !== undefined) {
        jobsAdapter.updateOne(state, { id, changes });
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getJobs.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getJobs.rejected, (state) => {
        state.status = 'idle';
      })
      .addCase(getJobs.fulfilled, (state, action) => {
        const { totalCount, jobs } = action.payload;
        state.status = 'complete';
        state.totalCount = totalCount;
        jobsAdapter.setAll(state, jobs);
      })
      .addCase(getJob.fulfilled, (state, action) => {
        jobsAdapter.setOne(state, action.payload);
      })
      .addCase(getJobsByScanId.fulfilled, (state, action) => {
        state.status = 'complete';
        jobsAdapter.setAll(state, action.payload);
      .addCase(cancelJob.fulfilled, (state, action) => {
        jobsAdapter.setOne(state, action.payload);
      });
  },
});

export const jobsSelector = jobsAdapter.getSelectors<RootState>(
  (state) => state.jobs
);

const jobState = (rootState: RootState) => rootState.jobs;
const { selectById, selectAll } = jobsAdapter.getSelectors();
export const jobSelector = (id: IdType) => {
  return createSelector(jobState, (state) => selectById(state, id));
};

export const allJobsSelector = createSelector(jobState, selectAll);

export const totalCount = (state: RootState) => state.jobs.totalCount;

export const { setJob, updateJob } = jobsSlice.actions;

export default jobsSlice.reducer;
